### PR TITLE
Provide an option to inverse the generated tf

### PR DESCRIPTION
**Pull request by ma-shangao**
Hi George,

Thank you for this handy odom to tf tool. It saved my day!

I added a new feature to allow users to create an inversed tf (base_link to odom), which could be helpful for the tf tree structure in certain cases.

Let me know what you think.

Kind regards,
Song

### CODE REVIEW

**Comment by gstavrinos** [comment]
Hey Song, thanks for the interest and the PR. I am glad that the package helped you!

I am not negative on merging this PR, but could you please provide me with a real-life example on how this inversion would help?

Thanks!

**Comment by ma-shangao** [comment]
> Hey Song, thanks for the interest and the PR. I am glad that the package helped you!
> 
> I am not negative on merging this PR, but could you please provide me with a real-life example on how this inversion would help?
> 
> Thanks!

Hey George,

Thank you for the promp reply! Sure, here is the case I encountered.

In my case, I want to simulate a robot in Gazebo. The robot could localise itself with sensors like IMU and GPS. This localisation by internal sensors is represented by a transformation of `map/odom -> base_link`. Besides, I also have an odometry topic provided by the Gazebo p3d as the ground truth localisation result, where the `frame_id` is `world` and the `child_frame_id` is `base_link`. 

Because the `base_link` frame cannot have two parent frames, I cannot host `world`, `map/odom`, and `base_link` frames together to compare the `world` and `map/odom`.  A workaround could be broadcasting an inversed tf of the ground truth odometry topic, which provides a complete tf tree with all required frames as: `map/odom -> base_link -> world`. Such a tf tree could reveal the error of the localisation system in a very straightforward way.

Let me know if you think this feature suits the context of the package.

Thank you!

**Comment by gstavrinos** [comment]
Thanks for the explanation, Song. I don't see any real reason not to offer the option for future users. I will come back with an overall formatting commit and merge your PR, asap! Thanks for your effort!

**Review by gstavrinos — APPROVED** [review]

**Comment by gstavrinos** [comment]
A year later, I have submitted your updates to rosdistro, @ma-shangao. Sorry for the **HUGE** delay and thanks again!

**Pull request merged**
